version : "2"

networks:
  pysock:
  db:

volumes: 
  webglbuild:
  mariadata:

services:
  maria:
    image: mariadb:10.4 
    #ports:
      #- 3306:3306 # !!!!!!!!!!!!!!!!! Do not expose this in production (i.e. dont change this unless testing db) !!!!!!!!!!!!!!!!!!!!!!
    env_file:
      - ./maria/default.env
    networks:
      - db
    volumes:
      - ./maria/sqlscripts/:/docker-entrypoint-initdb.d/
      - mariadata:/var/lib/mysql
  roomio:
    build:
      context: ./roomio-server
      dockerfile: ./dockerfile
    volumes:
      - ../server/server:/usr/src/app/server
    networks:
      - db
      - pysock

  nginx:
    image: nginx:1.14
    volumes:
      - ./nginx-server/nginx.conf:/etc/nginx/conf.d/mysite.template
      - webglbuild:/etc/nginx/html/
    ports:
      - 80:80
    command: /bin/bash -c "envsubst '$${API_LOCATION},$${UI_LOCATION}' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - pysock
    depends_on:
      - roomio

  unity:
    image: gableroux/unity3d:latest
    volumes: 
      - webglbuild:/root/project/build/
      - ../CSCE315Project2:/root/project/
      - ./unity/Unity_v2018.x.ulf:/root/.local/share/unity3d/Unity/Unity_lic.ulf
    environment:
      - TEST_PLATFORM=linux
      - WORKDIR=/root/project
    command: /opt/Unity/Editor/Unity -nographics -batchmode -quit -logFile /root/project/stderr.log -projectPath /root/project -executeMethod WebGLBuilder.build
    #command: xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity -logFile -batchmode -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD"
    #command: xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity -nographics -batchmode -quit -logFile stderr.log -projectPath /root/project -executeMethod WebGLBuilder.build

