version : "2"
networks:
  pysock:
services:
  websocket:
    build:
      context: ./websocket-server
      dockerfile: ./dockerfile
    volumes:
      - ../server:/usr/src/app/server
    networks:
      - pysock

  nginx:
    image: nginx:1.14
    volumes:
      - ./nginx-server/nginx.conf:/etc/nginx/conf.d/mysite.template
      - ../index.html:/etc/nginx/html/index.html
    ports:
      - 8080:8080
    command: /bin/bash -c "envsubst '$${API_LOCATION},$${UI_LOCATION}' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - pysock
    depends_on:
      - websocket